ads/urls.py
from django.urls import path
from .views import sidebaner_count

app_name = 'ads'
urlpatterns = [
    path('боковой_баннер/<int:pk>', sidebaner_count, name='sidebanner_count'),
]

credit/urls.py
from django.urls import path
from .views import CreditOfferView

app_name = 'credit'
urlpatterns = [
    path('организация/<str:slug>', CreditOfferView.as_view(), name='offer'),
]

kreditobzor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from .utils import get_homepage as homepage
from.sitemaps import StaticSitemap, MFOSitemap, CreditSitemap, NewsSitemap, ArticleSitemap
from news.views import NewsView, ArticlesView
from manager.utils import referrer_count

sitemaps = {
    'static': StaticSitemap,
    'mfo': MFOSitemap,
    'credit': CreditSitemap,
    'news': NewsSitemap,
    'articles': ArticleSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('', homepage, name='home'),
    path('онлайн_займы/', include('mfo.urls', namespace='mfo')),
    path('кредитные_карты/', include('credit.urls')),
    path('новости/', NewsView.as_view(), name='news'),
    path('статьи/', ArticlesView.as_view(), name='articles'),
    path('новости_и_статьи/', include('news.urls')),
    path('реклама/', include('ads.urls')),
    path('manager/', include('manager.urls')),
    path('оформить/<str:app_name>/<int:pk>/', referrer_count, name='ref_count'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,)

    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),

                      # For django versions before 2.0:
                      # url(r'^__debug__/', include(debug_toolbar.urls)),

                  ] + urlpatterns

credit/models.py
from django.shortcuts import reverse
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator


class Offer(models.Model):
    active = models.BooleanField(default=True)
    slug = models.SlugField(allow_unicode=True, unique=True, verbose_name='URL')
    title = models.CharField(max_length=100, verbose_name='Название')
    image = models.ImageField(verbose_name='Логотип')
    description = models.TextField(max_length=4000, verbose_name='Описание')
    default_position = models.IntegerField(verbose_name='Дефолтная позиция')
    link = models.URLField(verbose_name='Ссылка')
    limit = models.IntegerField(verbose_name='Кредитный лимит')
    maintenance = models.IntegerField(verbose_name='Обслуживание')
    min_rate = models.DecimalField(max_digits=4, decimal_places=2, verbose_name='Ставка')
    special_offer = models.BooleanField(verbose_name='Специальное предложение')
    cashback = models.IntegerField(verbose_name='Кэшбэк', default=0)
    high_approval_rate = models.BooleanField(verbose_name='Высокий % одобрения')
    issue_cost = models.CharField(max_length=20, verbose_name='Открытие')
    courier = models.BooleanField(verbose_name='Доставка курьером')
    documents = models.CharField(max_length=50, verbose_name='Документы')
    history_rating = models.IntegerField(verbose_name='Кредитный рейтинг')
    advantage1 = models.CharField(max_length=200, blank=True, null=True, verbose_name='Преимущество 1')
    advantage2 = models.CharField(max_length=200, blank=True, null=True, verbose_name='Преимущество 2')
    advantage3 = models.CharField(max_length=200, blank=True, null=True, verbose_name='Преимущество 3')
    advantage4 = models.CharField(max_length=200, blank=True, null=True, verbose_name='Преимущество 4')
    legal_info = models.TextField(max_length=2000, verbose_name='Юридическая информация')
    promoted = models.BooleanField(verbose_name='Продвигаемое')
    rating = models.DecimalField(max_digits=3, decimal_places=1, verbose_name='rating', default=0)
    count = models.IntegerField(verbose_name='Количество отзывов', default=0)
    clicked = models.IntegerField(verbose_name='Переходов', default=0)
    addition = models.TextField(max_length=4000, verbose_name='Дополнительный текст', blank=True, null=True)

    class Meta:
        ordering = ('default_position',)
        verbose_name = 'Оффер'
        verbose_name_plural = 'Офферы'

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('credit:offer', args=[str(self.slug)])


class Comment(models.Model):
    offer = models.ForeignKey(Offer, on_delete=models.CASCADE, related_name='comments', verbose_name='Оффер')
    author = models.CharField(max_length=50, verbose_name='Автор')
    date_created = models.DateTimeField(default=timezone.now, verbose_name='Дата написания')
    text = models.TextField(max_length=4000, verbose_name='Комментарий')
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], verbose_name='Оценка')

    class Meta:
        ordering = ('-date_created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.offer.title + ' - ' + self.author


class UnverifiedComment(models.Model):
    offer = models.ForeignKey(Offer, on_delete=models.CASCADE, related_name='unverified_comments', verbose_name='Оффер')
    author = models.CharField(max_length=50, verbose_name='Автор')
    date_created = models.DateTimeField(default=timezone.now, verbose_name='Дата написания')
    text = models.TextField(max_length=4000, verbose_name='Комментарий')
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], verbose_name='Оценка')
    ip = models.GenericIPAddressField()
    user_agent = models.CharField(max_length=1000)

    class Meta:
        ordering = ('-date_created',)
        verbose_name = 'Непроверенный комментарий'
        verbose_name_plural = 'Непроверенные комментарии'

    def __str__(self):
        return self.offer.title + ' - ' + self.author


class StashedComment(models.Model):
    author = models.CharField(max_length=50, verbose_name='Автор')
    date_created = models.DateTimeField(default=timezone.now, verbose_name='Дата написания')
    text = models.TextField(max_length=4000, verbose_name='Комментарий')
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], verbose_name='Оценка')

    class Meta:
        ordering = ('-date_created',)
        verbose_name = 'Комментарий из пула'
        verbose_name_plural = 'Комментарии из пула'

    def __str__(self):
        return self.date_created.strftime("%Y-%m-%d %H:%M:%S") + ' - ' + self.author

credit/views.py
from django.shortcuts import redirect, reverse
from django.conf import settings
from django.views.generic import ListView, DetailView
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from manager.utils import get_rating, get_count, referrer
from .models import Offer, Comment, UnverifiedComment
from ads.models import SidebarBanner
from manager.forms import CommentForm

app_list = settings.APP_LIST
app_name = 'кредитные_карты'


class CreditHomeView (ListView):

    model = Offer
    context_object_name = 'offers'
    paginate_by = 9
    template_name = 'home.html'

    def dispatch(self, request, *args, **kwargs):
        if 'h' in self.request.GET:
            if self.request.GET['h'] != app_name:
                for app in app_list:
                    if self.request.GET['h'] == app:
                        self.request.session['h'] = app
                        return redirect('home')
        return super(CreditHomeView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):

        referrer(self)

        quizonstart = 'n'

        filter_list = {'народный_выбор': 'народный выбор', 'высокое_одобрение': 'высокий % одобрения', 'процентная_ставка': 'по процентной ставке',
                       'цена_обслуживания': 'по цене обслуживания', 'кредитный_лимит': 'по кредитному лимиту', 'кэшбэк': 'по величине кэшбэка'}
        context = super().get_context_data(**kwargs)
        if 's' in self.request.GET:
            for key, value in filter_list.items():
                if self.request.GET['s'] == key:
                    context['filter'] = value
        else:
            context['filter'] = 'Сортировать по ...'
        context['filter_list'] = filter_list
        context['app_name'] = 'Кредитные карты'
        context['app_slug'] = 'credit'
        context['sidebanners'] = SidebarBanner.objects.filter(reference_app=app_name).filter(enabled=True)
        context['qz'] = quizonstart
        return context

    def get_queryset(self):
        if 's' in self.request.GET:
            if self.request.GET['s'] == 'народный_выбор':
                return Offer.objects.filter(active=True).order_by('-rating')
            if self.request.GET['s'] == 'высокое_одобрение':
                return Offer.objects.filter(active=True).order_by('-high_approval_rate')
            if self.request.GET['s'] == 'процентная_ставка':
                return Offer.objects.filter(active=True).order_by('min_rate')
            if self.request.GET['s'] == 'кредитный_лимит':
                return Offer.objects.filter(active=True).order_by('-limit')
            if self.request.GET['s'] == 'кэшбэк':
                return Offer.objects.filter(active=True).order_by('-cashback')
            if self.request.GET['s'] == 'цена_обслуживания':
                return Offer.objects.filter(active=True).order_by('maintenance')
        else:
            return Offer.objects.all()


class CreditOfferView (DetailView):

    model = Offer
    template_name = 'offer.html'
    context_object_name = 'offer'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comments = Comment.objects.filter(offer=self.object)
        paginator = Paginator(comments, self.paginate_by)

        referrer(self)

        quizonstart = 'n'

        page = self.request.GET.get('page')

        try:
            comments = paginator.page(page)
        except PageNotAnInteger:
            comments = paginator.page(1)
        except EmptyPage:
            comments = paginator.page(paginator.num_pages)

        context['comments'] = comments
        context['page_obj'] = comments
        context['form'] = CommentForm
        context['app_name'] = 'Кредитные карты'
        context['app_slug'] = 'credit'
        context['sidebanners'] = SidebarBanner.objects.filter(reference_app=app_name).filter(enabled=True)
        context['promoted_offers'] = Offer.objects.filter(active=True, promoted=True)
        context['qz'] = quizonstart
        return context

    def post(self, request, **kwargs):
        slug = self.request.POST['organization']
        offer = Offer.objects.get(slug=slug)
        if self.request.user.is_authenticated:
            new_comment = Comment(offer=offer, author=self.request.POST['author'], text=self.request.POST['text'], rating=self.request.POST['hidden-rating'])
            new_comment.save()
            offer.rating = get_rating(offer)
            offer.count = get_count(offer)
            offer.save()
        else:
            new_comment = UnverifiedComment(offer=offer, author=self.request.POST['author'], text=self.request.POST['text'], rating=self.request.POST['hidden-rating'])
            new_comment.save()
        return HttpResponseRedirect(reverse('credit:offer', kwargs={'slug': slug}))

templates/credit/card.html
{% load static %}
{% load site_tags %}
<div class="card">
    <div class="row row-1">
        {% if offer.special_offer is True %}
            <div class="plank green">
                <p>Кэшбэк до {{ offer.cashback }}%</p>
            </div>
        {% endif %}
        {% if offer.rating >= 8 %}
            <div class="plank red">
                <p>Народный выбор</p>
            </div>
        {% endif %}
        {% if offer.high_approval_rate is True %}
            <div class="plank blue">
                <p>Высокий % одобрения</p>
            </div>
        {% endif %}
    </div>
    <div class="row row-2">
        <div class="col">
            <p>{{ offer.title }}</p>
        </div>
        <div class="col">
            <p>Кредитный лимит</p>
        </div>
        <div class="col">
            <p>Обслуживание</p>
        </div>
        <div class="col">
            <p>Процентная ставка</p>
        </div>
        <div class="col">
            <h4> {% comments_count offer %} </h4>
        </div>
    </div>
    <div class="row row-3">
        <div class="col">
            <a href="{% url 'ref_count' 'кредитные_карты' offer.pk %}" target="_blank" rel="nofollow"><img src="{{ offer.image.url }}" alt="КредитОбзор.рф - отзывы о {{ offer.title }}."></a>
            <a href="{% url 'ref_count' 'кредитные_карты' offer.pk %}" target="_blank" rel="nofollow"><button>Оформить</button></a>
            {% if user.is_authenticated %}<p class="redirects">Переходов: {{ offer.clicked }}</p>{% endif %}
        </div>
        <div class="col">
            <div class="row row-1">
                <div class="col">
                    <h3>до {{ offer.limit }}</h3>
                    <p>рублей</p>
                </div>
                <div class="col">
                    <h3>{{ offer.maintenance }}</h3>
                    <p>рублей</p>
                </div>
                <div class="col">
                    <h3>от {{ offer.min_rate }}%</h3>
                    <p>в год</p>
                </div>
                <div class="col">
                    <a href="{% if app_name == 'Займы' %} {% url 'mfo:offer' offer.slug %} {% elif app_name == 'Кредитные карты' %} {% url 'credit:offer' offer.slug %} {% endif %}"><button>Читать отзывы</button></a>
                </div>
            </div>
            <div class="row row-2">
                <div class="col">
                    <div class="row">
                        <img src="{% static 'img/icon-issue.jpg' %}" alt="открытие кредитной карты">
                        <p>Открытие: {{ offer.issue_cost }} руб.</p>
                    </div>
                    <div class="row">
                        <img src="{% static 'img/icon-delivery.jpg' %}" alt="доставка кредитной карты">
                        <p>Доставка курьером: {% if offer.courier is True%} Да {% else %} Нет {% endif %}</p>
                    </div>
                    <div class="row">
                        <img src="{% static 'img/icon-pass.png' %}" alt="какие документы нужны для кредитной карты">
                        <p>Документы: {{ offer.documents }}</p>
                    </div>
                </div>
                <div class="col">
                    <p>Требуемый кредитный рейтинг - {{ offer.history_rating }}</p>
                    <br>
                    {% if offer.special_offer is True %}
                        <p class="green">Кэшбек</p>
                        <p>Кэшбэк до {{ offer.cashback }}%</p>
                    {% endif %}
                </div>
                <div class="col">
                    <h3>Рейтинг - {{ offer.rating }} </h3>
                    <div class="rating {{ offer.title }}-rating"></div>
                        <script>
                        $(".{{ offer.title }}-rating").starRating({
                            starSize: 1.5,
                            initialRating: {% star_rating offer %},
                            readOnly: true,
                            strokeWidth: 0,
                            activeColor: '#fab309',
                            hoverColor: '#feca15',
                            ratedColor: '#facf09',
                            starShape: 'rounded',
                        });
                        </script>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="mobile-card">
    <div class="row">
        <div class="col">
            <a href="{% url 'ref_count' 'кредитные_карты' offer.pk %}" target="_blank" rel=“nofollow”><img src="{{ offer.image.url }}" alt="КредитОбзор.рф - отзывы о {{ offer.title }}."></a>
            {% if user.is_authenticated %}<p class="redirects">Переходов: {{ offer.clicked }}</p>{% endif %}
            {% if offer.special_offer is True %}
                <div class="plank green">
                    <p>Кэшбэк до {{ offer.cashback }}%</p>
                </div>
            {% endif %}
            {% if offer.rating >= 8 %}
                <div class="plank red">
                    <p>Народный выбор</p>
                </div>
            {% endif %}
            {% if offer.high_approval_rate is True %}
                <div class="plank blue">
                    <p>Высокий % одобрения</p>
                </div>
            {% endif %}
        </div>
        <div class="col">
            <p>{{ offer.title }}</p>
            <h3>Рейтинг - {{ offer.rating }} </h3>
            <div class="rating {{ offer.title }}-rating"></div>
            <script>
                $(".{{ offer.title }}-rating").starRating({
                    starSize: 5,
                    initialRating: {% star_rating offer %},
                    readOnly: true,
                    strokeWidth: 0,
                    activeColor: '#fab309',
                    hoverColor: '#feca15',
                    ratedColor: '#facf09',
                    starShape: 'rounded',
                });
            </script>
            <a href="{% url 'ref_count' 'кредитные_карты' offer.pk %}" target="_blank" rel="nofollow"><button>Оформить</button></a>
        </div>
    </div>
    <div class="row">
        <div class="row">
            <div class="col">
                <p>Кредитный лимит</p>
                <div class="row">
                    <h3>до {{ offer.limit }}</h3>
                    <p>&nbsp;рублей</p>
                </div>
            </div>
            <div class="col">
                <p>Обслуживание</p>
                <div class="row">
                    <h3>{{ offer.maintenance }}</h3>
                    <p>&nbsp;рублей</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <p>Процентная ставка</p>
                <div class="row">
                    <h3>от {{ offer.min_rate }}%</h3>
                    <p>&nbsp;в год</p>
                </div>
            </div>
            <div class="col">
                <p>Открытие</p>
                <div class="row">
                    <img src="{% static 'img/icon-issue.jpg' %}" alt="открытие кредитной карты">
                    <h3>{{ offer.issue_cost }} руб.</h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <p>Доставка курьером</p>
                <div class="row">
                    <img src="{% static 'img/icon-delivery.jpg' %}" alt="доставка кредитной карты">
                    <h3>{% if offer.courier is True%} Да {% else %} Нет {% endif %}</h3>
                </div>
            </div>
            <div class="col">
                <p>Документы</p>
                <div class="row">
                    <img src="{% static 'img/icon-pass.png' %}" alt="какие документы нужны для займа">
                    <h3>{{ offer.documents }}</h3>
                </div>
            </div>
        </div>
        <div class="row">
            <p>Требуемый кредитный рейтинг</p>
            <h3>{{ offer.history_rating }}</h3>
        </div>
    </div>
    <div class="row">
        {% if offer.special_offer is True %}
            <div class="green-border">
                <p class="green">Кэшбек</p>
                <p>Кэшбэк до {{ offer.cashback }}%</p>
            </div>
        {% endif %}
    </div>
    <div class="row">
        <h4>{% comments_count offer %}</h4>
        <a href="{% url 'credit:offer' offer.slug %}"><button>Читать отзывы</button></a>
    </div>
</div>

templates/credit/detail-card.html
{% load static %}
{% load site_tags %}
<div class="offer-card">
    <div class="row">
        <h3>Отзывы о компании {{ offer.title }}</h3>
        <div class="row">
            <div class="{{ offer.title }}-rating"></div>
            <h3>Рейтинг - {{ offer.rating }}</h3>
            <script>
                $(".{{ offer.title }}-rating").starRating({
                    starSize: 1.5,
                    initialRating: {% star_rating offer %},
                    readOnly: true,
                    strokeWidth: 0,
                    activeColor: '#fab309',
                    hoverColor: '#feca15',
                    ratedColor: '#facf09',
                    starShape: 'rounded',
                });
            </script>
        </div>
    </div>
    <div class="card">
        <div class="row row-2">
            <div class="d-col">
                <p>{{ offer.title }}</p>
            </div>
            <div class="d-col">
                <p>Кредитный лимит</p>
            </div>
            <div class="d-col">
                <p>Обслуживание</p>
            </div>
            <div class="d-col">
                <p>Процентная ставка</p>
            </div>
        </div>
        <div class="row row-3">
            <div class="d-col">
                <a href="{% url 'ref_count' 'кредитные_карты' offer.pk %}" target="_blank" rel="nofollow"><img src="{{ offer.image.url }}" alt="КредитОбзор.рф - отзывы о {{ offer.title }}."></a>
                <a href="{% url 'ref_count' 'кредитные_карты' offer.pk %}" target="_blank" rel="nofollow"><button>Оформить</button></a>
            </div>
            <div class="d-col">
                <div class="row row-1">
                    <div class="col">
                        <h3>до {{ offer.limit }}</h3>
                        <p>рублей</p>
                    </div>
                    <div class="col">
                        <h3>{{ offer.maintenance }}</h3>
                        <p>рублей</p>
                    </div>
                    <div class="col">
                        <h3>от {{ offer.min_rate }}%</h3>
                        <p>в год</p>
                    </div>
                </div>
                <div class="row row-2">
                    <div class="col">
                        <div class="row">
                            <img src="{% static 'img/icon-issue.jpg' %}" alt="открытие кредитной карты">
                            <p>Открытие: {{ offer.issue_cost }} руб.</p>
                        </div>
                        <div class="row">
                            <img src="{% static 'img/icon-delivery.jpg' %}" alt="доставка кредитной карты">
                            <p>Доставка курьером: {% if offer.courier is True%} Да {% else %} Нет {% endif %}</p>
                        </div>
                        <div class="row">
                            <img src="{% static 'img/icon-pass.png' %}" alt="какие документы нужны для кредитной карты">
                            <p>Документы: {{ offer.documents }}</p>
                        </div>
                    </div>
                    <div class="col">
                        <p>Требуемый кредитный рейтинг - {{ offer.history_rating }}</p>
                        <br>
                        {% if offer.special_offer is True %}
                            <p class="green">Кэшбек</p>
                            <p>Кэшбэк до {{ offer.cashback }}%</p>
                        {% endif %}
                    </div>
                </div>
                <div class="row row-3">
                    <div class="advantages">
                    {% if offer.advantage1 is not None %}<div><p>{{ offer.advantage1 }}</p></div>{% endif %}
                    {% if offer.advantage2 is not None %}<div><p>{{ offer.advantage2 }}</p></div>{% endif %}
                    {% if offer.advantage3 is not None %}<div><p>{{ offer.advantage3 }}</p></div>{% endif %}
                    {% if offer.advantage4 is not None %}<div><p>{{ offer.advantage4 }}</p></div>{% endif %}
                    </div>
                </div>
                <div class="row row-4">
                    <div class="addition">
                        <p>{{ offer.addition }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mobile-card nomargin">
        <div class="row">
            <div class="col">
                <a href="{% url 'ref_count' 'кредитные_карты' offer.pk %}" target="_blank" rel="nofollow"><img src="{{ offer.image.url }}" alt="КредитОбзор.рф - отзывы о {{ offer.title }}."></a>
                {% if offer.special_offer is True %}
                    <div class="plank green">
                        <p>Кэшбэк до {{ offer.cashback }}%</p>
                    </div>
                {% endif %}
                {% if offer.rating >= 8 %}
                    <div class="plank red">
                        <p>Народный выбор</p>
                    </div>
                {% endif %}
                {% if offer.high_approval_rate is True %}
                    <div class="plank blue">
                        <p>Высокий % одобрения</p>
                    </div>
                {% endif %}
            </div>
            <div class="col">
                <p></p>
                <p>{{ offer.title }}</p>
                <h3>Рейтинг - {{ offer.rating }} </h3>
                <div class="rating {{ offer.title }}-rating"></div>
                <script>
                    $(".{{ offer.title }}-rating").starRating({
                        starSize: 5,
                        initialRating: {% star_rating offer %},
                        readOnly: true,
                        strokeWidth: 0,
                        activeColor: '#fab309',
                        hoverColor: '#feca15',
                        ratedColor: '#facf09',
                        starShape: 'rounded',
                    });
                </script>
                <a href="{% url 'ref_count' 'кредитные_карты' offer.pk %}" target="_blank" rel="nofollow"><button>Оформить</button></a>
            </div>
        </div>
        <div class="row">
            <div class="row">
                <div class="col">
                    <p>Кредитный лимит</p>
                    <div class="row">
                        <h3>до {{ offer.limit }}</h3>
                        <p>&nbsp;рублей</p>
                    </div>
                </div>
                <div class="col">
                    <p>Обслуживание</p>
                    <div class="row">
                        <h3>{{ offer.maintenance }}</h3>
                        <p>&nbsp;рублей</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <p>Процентная ставка</p>
                    <div class="row">
                        <h3>от {{ offer.min_rate }}%</h3>
                        <p>&nbsp;в год</p>
                    </div>
                </div>
                <div class="col">
                    <p>Открытие</p>
                    <div class="row">
                        <img src="{% static 'img/icon-issue.jpg' %}" alt="открытие кредитной карты">
                        <h3>{{ offer.issue_cost }} руб.</h3>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <p>Доставка курьером</p>
                    <div class="row">
                        <img src="{% static 'img/icon-delivery.jpg' %}" alt="доставка кредитной карты">
                        <h3>{% if offer.courier is True%} Да {% else %} Нет {% endif %}</h3>
                    </div>
                </div>
                <div class="col">
                    <p>Документы</p>
                    <div class="row">
                        <img src="{% static 'img/icon-pass.png' %}" alt="какие документы нужны для займа">
                        <h3>{{ offer.documents }}</h3>
                    </div>
                </div>
            </div>
            <div class="row">
                <p>Требуемый кредитный рейтинг</p>
                <h3>{{ offer.history_rating }}</h3>
            </div>
        </div>
        <div class="row">
            {% if offer.special_offer is True %}
                <div class="green-border">
                    <p class="green">Кэшбек</p>
                    <p>Кэшбэк до {{ offer.cashback }}%</p>
                </div>
            {% endif %}
        </div>
        <div class="row">
            <div class="advantages">
            {% if offer.advantage1 is not None %}<div><p>{{ offer.advantage1 }}</p></div>{% endif %}
            {% if offer.advantage2 is not None %}<div><p>{{ offer.advantage2 }}</p></div>{% endif %}
            {% if offer.advantage3 is not None %}<div><p>{{ offer.advantage3 }}</p></div>{% endif %}
            {% if offer.advantage4 is not None %}<div><p>{{ offer.advantage4 }}</p></div>{% endif %}
            </div>
        </div>
        <div class="row">
            <div class="addition">
                <p>{{ offer.addition }}</p>
            </div>
        </div>
        <div class="row">
            <h4>{% comments_count offer %}</h4>
        </div>
    </div>
</div>