ads/urls.py
from django.urls import path
from .views import sidebaner_count

app_name = 'ads'
urlpatterns = [
    path('боковой_баннер/<int:pk>', sidebaner_count, name='sidebanner_count'),
]

credit/urls.py
from django.urls import path
from .views import CreditOfferView

app_name = 'credit'
urlpatterns = [
    path('организация/<str:slug>', CreditOfferView.as_view(), name='offer'),
]

kreditobzor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from .utils import get_homepage as homepage
from.sitemaps import StaticSitemap, MFOSitemap, CreditSitemap, NewsSitemap, ArticleSitemap
from news.views import NewsView, ArticlesView
from manager.utils import referrer_count

sitemaps = {
    'static': StaticSitemap,
    'mfo': MFOSitemap,
    'credit': CreditSitemap,
    'news': NewsSitemap,
    'articles': ArticleSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('', homepage, name='home'),
    path('онлайн_займы/', include('mfo.urls', namespace='mfo')),
    path('кредитные_карты/', include('credit.urls')),
    path('новости/', NewsView.as_view(), name='news'),
    path('статьи/', ArticlesView.as_view(), name='articles'),
    path('новости_и_статьи/', include('news.urls')),
    path('реклама/', include('ads.urls')),
    path('manager/', include('manager.urls')),
    path('оформить/<str:app_name>/<int:pk>/', referrer_count, name='ref_count'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,)

    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),

                      # For django versions before 2.0:
                      # url(r'^__debug__/', include(debug_toolbar.urls)),

                  ] + urlpatterns

manager/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.manager, name='manager'),
    path('mfo/accept/<int:comment_id>-<str:app>', views.accept_comment, name='accept-comment'),
    path('mfo/delete/<int:comment_id>-<str:app>', views.delete_comment, name='delete-comment'),
    path('mfo/edit/<int:comment_id>-<str:app>', views.edit_comment, name='edit-comment'),
    path('send_push/', views.send_push, name='push'),
    path('subscribe', views.subscription, name='subscription'),
    path('referals', views.referals, name='referals'),
    path('comments', views.comments, name='comments'),
    path('distribute-stashed/<str:app>', views.distribute_stashed, name='distribute-stashed')
]

news/urls.py
from django.urls import path
from .views import NewsDetailView, ArticlesDetailView

app_name = 'news'
urlpatterns = [
    path('новость/<int:pk>', NewsDetailView.as_view(), name='news_detail'),
    path('статья/<int:pk>', ArticlesDetailView.as_view(), name='article_detail'),
]

manager/models.py
from urllib.parse import urlparse

from django.db import models
from django.utils import timezone


class TeaserClick (models.Model):
    link = models.URLField(verbose_name='Ссылка')
    banner = models.CharField(max_length=100, verbose_name='Баннер')
    ip = models.GenericIPAddressField(verbose_name='IP')
    useragent = models.CharField(max_length=250, verbose_name='User agent')
    timestamp = models.DateTimeField(default=timezone.now, verbose_name='Время')
    referer = models.CharField(max_length=500, default='Нет реферера', verbose_name='Реферер')
    cookie_counter = models.IntegerField(verbose_name='Переходов по куки')
    geo = models.CharField(max_length=100, default='Нет информации', verbose_name='ГЕО')
    age = models.CharField(max_length=100, default='Нет информации', verbose_name='Возраст')
    gender = models.CharField(max_length=100, default='Нет информации ', verbose_name='Пол')
    search = models.CharField(max_length=1000, default='Нет информации ', verbose_name='Поисковая фраза')

    class Meta:
        ordering = ('-timestamp',)
        verbose_name = 'Тизерный клик'
        verbose_name_plural = 'Тизерные клики'

    def __str__(self):
        return self.timestamp.strftime("%Y-%m-%d %H:%M:%S") + ' ' + self.banner


class TeaserLead (models.Model):
    timestamp = models.DateTimeField(default=timezone.now, verbose_name='Время')
    offer = models.CharField(max_length=100, verbose_name='Оффер')
    banner = models.CharField(max_length=1000, verbose_name='Идентификатор')
    ip = models.GenericIPAddressField(verbose_name='IP')
    geo = models.CharField(max_length=100, default='Нет информации', verbose_name='ГЕО')
    age = models.CharField(max_length=100, default='Нет информации', verbose_name='Возраст')
    gender = models.CharField(max_length=100, default='Нет информации', verbose_name='Пол')
    search = models.CharField(max_length=1000, default='Нет информации', verbose_name='Поисковая фраза')
    cookie_counter = models.IntegerField(default=0, verbose_name='Переходов по офферам')

    class Meta:
        ordering = ('-timestamp',)
        verbose_name = 'Тизерный лид'
        verbose_name_plural = 'Тизерные лиды'

    def __str__(self):
        return self.timestamp.strftime("%Y-%m-%d %H:%M:%S") + ' ' + self.offer

manager/forms.py
from django import forms


class CommentForm (forms.Form):
    author = forms.CharField(max_length=50, label='Имя')
    text = forms.CharField(max_length=4000, widget=forms.Textarea,label='Комментарий')

manager/views.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponse
from django.utils import timezone
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q

from django.conf import settings
from manager.utils import get_rating, get_count
from mfo.models import Offer as MFOOffer
from mfo.models import Comment as MFOComment
from mfo.models import UnverifiedComment as MFOUnverifiedComment
from mfo.models import StashedComment as MFOStashedComment
from credit.models import Offer as CreditOffer
from credit.models import Comment as CreditComment
from credit.models import UnverifiedComment as CreditUnverifiedComment
from credit.models import StashedComment as CreditStashedComment
from .models import TeaserClick, TeaserLead

from django.views.decorators.csrf import csrf_exempt

import json
from push_notifications.models import WebPushDevice
from push_notifications.webpush import WebPushError

import datetime
import random
from urllib.parse import urlparse
from collections import Counter


def manager(request):
    if request.user.is_authenticated:
        mfo_comments = MFOUnverifiedComment.objects.all()
        credit_comments = CreditUnverifiedComment.objects.all()
        webpush_settings = getattr(settings, 'WEBPUSH_SETTINGS', {})
        context = {
            'mfo_comments': mfo_comments,
            'credit_comments': credit_comments,
            'vapid_key': webpush_settings.get('VAPID_PUBLIC_KEY'),
            'user': request.user,
        }
        return render(request, 'manager.html', context)
    else:
        return redirect('home')


def accept_comment(request, comment_id, app):
    if request.user.is_authenticated:
        if app == 'mfo':
            comment = MFOUnverifiedComment.objects.get(id=comment_id)
            new_comment = MFOComment(offer=comment.offer, author=comment.author, text=comment.text, rating=comment.rating, date_created=comment.date_created)
        elif app == 'credit':
            comment = CreditUnverifiedComment.objects.get(id=comment_id)
            new_comment = CreditComment(offer=comment.offer, author=comment.author, text=comment.text, rating=comment.rating, date_created=comment.date_created)
        comment.delete()
        new_comment.save()
        comment.offer.rating = get_rating(comment.offer)
        comment.offer.count = get_count(comment.offer)
        comment.offer.save()
        return manager(request)
    else:
        return redirect('home')


def delete_comment(request, comment_id, app):
    if request.user.is_authenticated:
        if app == 'mfo':
            comment = MFOUnverifiedComment.objects.get(id=comment_id)
            comment.delete()
        elif app == 'mfo_verified':
            comment = MFOComment.objects.get(id=comment_id)
            comment.delete()
            comment.offer.rating = get_rating(comment.offer)
            comment.offer.count = get_count(comment.offer)
            comment.offer.save()
            return redirect('mfo:offer', comment.offer.slug)
        elif app == 'mfo_stashed':
            comment = MFOStashedComment.objects.get(id=comment_id)
            comment.delete()
            return redirect('comments')
        elif app == 'credit':
            comment = CreditUnverifiedComment.objects.get(id=comment_id)
            comment.delete()
        elif app == 'credit_verified':
            comment = CreditComment.objects.get(id=comment_id)
            comment.delete()
            comment.offer.rating = get_rating(comment.offer)
            comment.offer.count = get_count(comment.offer)
            comment.offer.save()
            return redirect('credit:offer', comment.offer.slug)
        elif app == 'credit_stashed':
            comment = CreditStashedComment.objects.get(id=comment_id)
            comment.delete()
            return redirect('comments')
        return manager(request)
    else:
        return redirect('home')


def edit_comment(request, comment_id, app):
    if request.user.is_authenticated:
        if app == 'mfo':
            comment = MFOUnverifiedComment.objects.get(id=comment_id)
        elif app == 'mfo_verified':
            comment = MFOComment.objects.get(id=comment_id)
        elif app == 'mfo_stashed':
            comment = MFOStashedComment.objects.get(id=comment_id)
        elif app == 'credit':
            comment = CreditUnverifiedComment.objects.get(id=comment_id)
        elif app == 'credit_verified':
            comment = CreditComment.objects.get(id=comment_id)
        elif app == 'credit_stashed':
            comment = CreditStashedComment.objects.get(id=comment_id)
        if request.method == "POST":
            author = request.POST['author']
            text = request.POST['text']
            rating = request.POST['rating']
            date = request.POST['date']
            comment.author = author
            comment.text = text
            comment.rating = rating
            comment.date_created = date
            comment.save()
            if app == 'mfo_stashed' or app == 'credit_stashed':
                return redirect('comments')
            if app == 'mfo_verified' or app == 'credit_verified':
                comment.offer.rating = get_rating(comment.offer)
                comment.offer.save()
                if app == 'mfo_verified':
                    return redirect('mfo:offer', comment.offer.slug)
                if app == 'credit_verified':
                    return redirect('credit:offer', comment.offer.slug)
            return manager(request)
        else:
            isodate = comment.date_created.astimezone(timezone.get_current_timezone()).strftime("%Y-%m-%dT%H:%M")
            context = {
                'app': app,
                'comment': comment,
                'isodate': isodate,
            }
            return render(request, 'edit_comment.html', context)
    else:
        return redirect('home')


def send_push(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            if 'push_body' in request.POST:
                for device in WebPushDevice.objects.all():
                    try:
                        device.send_message(json.dumps({'message': request.POST['push_body'], 'title': request.POST['push_head'], 'tag': request.POST['push_url']}))
                    except WebPushError:
                        try:
                            device.browser = "FIREFOX"
                            device.save()
                            device.send_message(json.dumps({'message': request.POST['push_body'], 'title': request.POST['push_head'], 'tag': request.POST['push_url']}))
                        except WebPushError:
                            try:
                                device.browser = "OPERA"
                                device.save()
                                device.send_message(json.dumps({'message': request.POST['push_body'], 'title': request.POST['push_head'], 'tag': request.POST['push_url']}))
                            except WebPushError:
                                device.delete()
                                pass
                return render(request, 'push.html')
            return render(request, 'push.html')
        else:
            return render(request, 'push.html')
    else:
        return redirect('home')


def referals(request):
    if request.user.is_authenticated:
        referals = TeaserClick.objects.all()
        filter_list = {'netloc': 'Площадки', 'ip': 'IP', 'ua': 'Юзер агент', 'id': 'Идентификатор', 'gender': 'Пол', 'age': 'Возраст', 'geo': 'Гео', 'search': 'Поисковая фраза'}

        if 'r_m_d' not in request.session:
            request.session['r_m_d'] = '7'
        if 'r_m_d' in request.GET:
            request.session['r_m_d'] = request.GET['r_m_d']

        referals_date = TeaserClick.objects.filter(timestamp__gt=datetime.datetime.now() - datetime.timedelta(days=int(request.session['r_m_d'])))
        referals_lead = TeaserLead.objects.filter(timestamp__gt=datetime.datetime.now() - datetime.timedelta(days=int(request.session['r_m_d'])))

        if 's' in request.GET:
            if request.GET['s'] == 'ip':
                ip_list = []
                referals_list = {}
                for referal in referals_date:
                    ip_list.append(referal.ip)
                    referals_list.update({referal.timestamp.strftime("%Y-%m-%d %H:%M:%S"): referal.ip})
                referals_stat = dict(Counter(ip_list).most_common())
            elif request.GET['s'] == 'ua':
                ua_list = []
                referals_list = {}
                for referal in referals_date:
                    ua_list.append(referal.useragent)
                    referals_list.update({referal.timestamp.strftime("%Y-%m-%d %H:%M:%S"): referal.useragent})
                referals_stat = dict(Counter(ua_list).most_common())
            elif request.GET['s'] == 'id':
                id_list = []
                referals_list = {}
                for referal in referals_date:
                    id_list.append(referal.banner)
                    referals_list.update({referal.timestamp.strftime("%Y-%m-%d %H:%M:%S"): referal.banner})
                referals_stat = dict(Counter(id_list).most_common())
            elif request.GET['s'] == 'gender':
                gender_list = []
                referals_list = {}
                for referal in referals_date:
                    gender_list.append(referal.gender)
                    referals_list.update({referal.timestamp.strftime("%Y-%m-%d %H:%M:%S"): referal.gender})
                referals_stat = dict(Counter(gender_list).most_common())
            elif request.GET['s'] == 'age':
                age_list = []
                referals_list = {}
                for referal in referals_date:
                    age_list.append(referal.age)

news/views.py
from django.views.generic import ListView, DetailView

from manager.utils import get_app_offer
from .models import News, Article, Paragraph
from ads.models import SidebarBanner


class NewsView(ListView):
    model = News
    context_object_name = 'news'
    template_name = 'news.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['header'] = 'Новости'
        return context


class ArticlesView(ListView):
    model = Article
    context_object_name = 'news'
    template_name = 'news.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['header'] = 'Статьи'
        return context


class NewsDetailView(DetailView):
    model = News
    context_object_name = 'article'
    template_name = 'article.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sidebanners'] = SidebarBanner.objects.filter(reference_app=self.object.reference_app).filter(enabled=True)
        context['promoted_offers'] = get_app_offer(self.object.reference_app).objects.filter(active=True, promoted=True)
        return context


class ArticlesDetailView(DetailView):
    model = Article
    context_object_name = 'article'
    template_name = 'article.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sidebanners'] = SidebarBanner.objects.filter(reference_app=self.object.reference_app).filter(enabled=True)
        context['promoted_offers'] = get_app_offer(self.object.reference_app).objects.filter(active=True, promoted=True)
        context['paragraphs'] = Paragraph.objects.filter(article=self.object)
        return context

templates/article.html
{% extends 'base.html' %}
{% load static %}
{% block title %}КредитОбзор | {{ article.title }}{% endblock %}
{% block filters %}
    <div class="filter-placeholder"></div>
{% endblock %}
{% block main %}
<div class="main">
    <div class="article">
        <h3>{{ article.title }}</h3>
        <div class="article-header">
            <img src="{{ article.image.url }}" alt="{{ article.title }}">
            <p>{{ article.text | linebreaks }}</p>
        </div>
        {% for paragraph in paragraphs %}
        <div class="article-paragraph">
            <img src="{{ paragraph.image.url }}" alt="">
            <p>{{ paragraph.text | linebreaks }}</p>
        </div>
        {% endfor %}
    </div>
    <div class="promoted">
        <h5>Лучшие предложения</h5>
        {% for offer in promoted_offers %}
        {% include 'mfo/card.html' %}
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/base.html
{% load sass_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-154623264-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-154623264-1');
    </script>
    <!-- Global site tag (gtag.js) - Google Analytics -->

    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
       (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
       m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
       (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

       ym(56674468, "init", {
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true,
            webvisor:true
       });
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/56674468" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->

    <meta name="yandex-verification" content="25f7207673cd3f1f" />

    <meta charset="UTF-8">
    <title>{% block title %}КредитОбзор - сайт отзывов о кредитных картах, онлайн займах и других финансовых продуктах{% endblock %}</title>
    <meta name="description" content="{% block description %}Как получить займ в интернете? На сайте кредитобзор.рф вы найдете детальную информацию и отзывы о ведущих компаниях и микрофинансовых организациях, предоставляющих онлайн займы, а также кредитных картах и других финансовых продуктах{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="yandex-verification" content="fb17d5c655bbacc6" />
    <meta name="telderi" content="8d7092b81feb48a374ff42e39f25efa5" />
    <link rel="stylesheet" type="text/css" href="{% sass_src 'css/style.scss' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'css/star-rating-svg.css' %}">
    <link rel="icon" type="image/png" href="{% static 'img/favi.png' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery.star-rating-svg.js' %}"></script>

    {% block extra_head %}
    {% endblock %}
</head>
<body>
    {% if user.is_authenticated %}
        <div class="manager-button">
            <a href="{% url 'manager' %}"><img src="{% static 'img/boss.png' %}"></a>
        </div>
    {% endif %}
    <div class="nav-mobile" id="nav-mobile">
        <div class="nav-mobile-content">
            <span id="nav-close">&times;</span>
            <div class="nav-text">
                <a href="{% url 'home' %}">Рейтинг</a>
                <!-- <a href="{% url 'news' %}">Новости</a>
                <a href="{% url 'articles' %}">Статьи</a> !-->
                <a href="{% url 'home' %}?h=кредитные_карты">Кредитные карты</a>
                <a href="{% url 'home' %}?h=мфо">Онлайн Займы</a>
                <a id="open-quiz-menu">Умный подбор займа</a>
            </div>
        </div>
    </div>
    {% block quiz %}
    {% endblock %}
    <section class="header">
        <nav>
            <a href="{% url 'home' %}"><img src="{% static 'img/kreditobzor-logo.png' %}" alt="КредитОбзор - отзывы о займах на карту"></a>
            <a href="{% url 'home' %}"><p>Рейтинг</p></a>
            <!-- <a href="{% url 'news' %}"><p>Новости</p></a>
            <a href="{% url 'articles' %}"><p>Статьи</p></a> !-->
            <a href="{% url 'home' %}?h=кредитные_карты"><p>Кредитные карты</p></a>
            <a href="{% url 'home' %}?h=мфо"><p>Онлайн Займы</p></a>
            <div class="nav-menu" id="nav-menu">
                <img src="{% static 'img/menubutton.png' %}">
            </div>
        </nav>
        <div class="header-text">
            <h1>Народный рейтинг онлайн займов</h1>
            <h2>Отзывы об онлайн займах, кредитных картах и других финансовых продуктах</h2>
            <p>На нашем сайте вы можете прочитать и оставить отзыв, а также подобрать для себя подходящее финансовое
                предложение, основываясь на оценках и комментариях пользователей сайта</p>
        </div>
        {% block filters %}
            <div class="filters">
                <p>Сортировка</p>
                <div class="filters-list">
                    <select onChange="window.location.href=this.value">
                        <option value="" disabled selected>{{ app_name }}</option>
                        <option value="?h=мфо">Займы</option>
                        <option value="?h=кредитные_карты">Кредитные карты</option>
                    </select>
                    {% for key, value in filter_list.items %}
                    <a {% if filter == value %}class="active"{% endif %} href="/?s={{ key }}">
                        {{ value }}
                    </a>
                    {% endfor %}
                    <div class="mobile-filters">
                        <select onChange="window.location.href=this.value">
                            <option value="" disabled selected>{{ filter }}</option>
                            {% for key, value in filter_list.items %}
                                <option value="/?s={{ key }}">{{ value }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
        {% endblock %}
        <div class="girls">
            <img src="{% static 'img/kreditobzor-promo.jpg' %}" alt="займ онлайн">
        </div>
    </section>
    <section class="content">
        {% block main %}
        {% endblock %}
            {% block sidebar %}
            <div class="sidebar">
            {% if app_name == 'Займы' %}
            <div class="quiz-banner">
                <img src="{% static 'img/quiz.jpg' %}" alt="заполнить анкету на кредит" id="open-quiz">
            </div>
            {% endif %}
            {% for sidebanner in sidebanners %}
            <div class="sidebanner">
                <a href={% url 'ads:sidebanner_count' sidebanner.pk %}><img src="{{ sidebanner.image.url }}" alt="{{ sidebanner.title }}"></a>
            </div>
            {% endfor %}
            </div>
        {% endblock %}
    </section>
    <footer>
    {% block footer %}
    {% endblock %}
        <script type="application/javascript" src="{% static 'js/main.js' %}"></script>
        <script>
            // Utils functions:
            function urlBase64ToUint8Array (base64String) {
                    var padding = '='.repeat((4 - base64String.length % 4) % 4)
                    var base64 = (base64String + padding)
                            .replace(/\-/g, '+')
                            .replace(/_/g, '/')
                    var rawData = window.atob(base64)
                    var outputArray = new Uint8Array(rawData.length)
                    for (var i = 0; i < rawData.length; ++i) {
                            outputArray[i] = rawData.charCodeAt(i)
                    }
                    return outputArray;
            }

            var applicationServerKey = "BBUu0gcd9pE-C9k3uGbssazXMYYXN0xaMfVSy28vYKYIth-Uu8u1JWfcvXEZ3c_K5-VjSnyM5xxalgjpk6oz-Iw";


            // In your ready listener
                if ('serviceWorker' in navigator) {
                    // The service worker has to store in the root of the app
                    // http://stackoverflow.com/questions/29874068/navigator-serviceworker-is-never-ready
                    window.addEventListener('load', function() {
                    navigator.serviceWorker.register('{% static 'js/sw.js' %}').then(function (reg) {
                        event.waitUntil(clients.claim();
                        reg.pushManager.subscribe({
                            userVisibleOnly: true,
                            applicationServerKey: urlBase64ToUint8Array(applicationServerKey)
                        }).then(function (sub) {
                            var endpointParts = sub.endpoint.split('/');
                            var registration_id = endpointParts[endpointParts.length - 1];
                            var data = {
                                'p256dh': btoa(String.fromCharCode.apply(null, new Uint8Array(sub.getKey('p256dh')))),
                                'auth': btoa(String.fromCharCode.apply(null, new Uint8Array(sub.getKey('auth')))),
                                'registration_id': registration_id
                            };
                            requestPOSTToServer(data);
                        })

                    }).catch(function (err) {
                        console.log(':^(', err);
                    });
                    })
                }


                function requestPOSTToServer(data) {
                    $.post('{% url 'subscription' %}', {
                        'name': 'WebPush',
                        'browser': 'CHROME',
                        'p256dh': data.p256dh,
                        'auth': data.auth,
                        'registration_id': data.registration_id,
                        }
                    )
                }
        </script>
        <script src="//code-ya.jivosite.com/widget/Tu37loyAt2" async></script>
    </footer>
{% block extra_js %}
{% endblock %}
</body>
</html>

templates/edit_comment.html
{% extends 'base.html' %}
{% load static %}
{% block filters %}
    <div class="filter-placeholder"></div>
{% endblock %}
{% block main %}
<div class="main-full">
    <div class="comment-form">
        <h3>Редактировать комментарий {{ app }}</h3>
        <form method="post" action="{% url 'edit-comment' comment.pk app %}">
            {% csrf_token %}
            <label>Автор: </label>
            <input name="author" value="{{ comment.author }}">
            <label>Комментарий: </label>
            <textarea name="text">{{ comment.text }}</textarea>
            <label>Оценка: </label>
            <input type="number" name="rating" value="{{ comment.rating }}">
            <label>Текущая дата: {{ comment.date_created }}. Изменить: </label>
            <input type="datetime-local" name="date" value="{{ isodate }}">
            <button type="submit" id="form-button">Отправить</button>
        </form>
    </div>
</div>
{% endblock %}
{% block sidebar %}
{% endblock %}

templates/news.html
{% extends 'base.html' %}
{% load static %}
{% block filters %}
    <div class="filter-placeholder"></div>
{% endblock %}
{% block main %}
<div class="main-full">
    <h3 class="news-header">{{ header }}</h3>
    <div class="news">
        {% for article in news %}
            {% if header == 'Новости' %}
            <a href="{% url 'news:news_detail' article.pk %}">
            {% elif header == 'Статьи' %}
            <a href="{% url 'news:article_detail' article.pk %}">
            {% endif %}
                <div class="news-box">
                    <img src="{{ article.image.url }}" alt="{{ article.title }}">
                    <p>{{ article.title }}</p>
                </div>
            </a>
        {% endfor %}
    </div>
    <div class="pagination">
        {% if page_obj.has_previous %}
            <a href="?page=1"><<</a>
            <a href="?page={{ page_obj.previous_page_number }}"><</a>
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
        <span class="page-current">
            {{ page_obj.number }}
        </span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
            <a href="?page={{ page_obj.next_page_number }}">></a>
            <a href="?page={{ page_obj.paginator.num_pages }}">>></a>
        {% endif %}
    </div>
</div>
{% endblock %}
{% block sidebar %}
{% endblock %}

templates/push.html
{% extends 'base.html' %}
{% load static %}
{% block extra_head %}
{% endblock %}
{% block filters %}
    <div class="filter-placeholder"></div>
{% endblock %}
{% block main %}
<div class="main-full">
    <div class="comment-form">
        <form class="comment-form" method="post" action="{% url 'push' %}">
            {% csrf_token %}
            <h3>Отправить ПУШ</h3>
            <p class="error"></p>
            <label>Заголовок: </label>
            <input type="text" name="push_head" >
            <label>Текст: </label>
            <textarea name="push_body" cols="30" rows="10"></textarea>
            <label>URL: </label>
            <input type="text" name="push_url" value="https://www.кредитобзор.рф" >
            <button>Отправить</button>
        </form>
    </div>
</div>
{% endblock %}
{% block sidebar %}
{% endblock %}
{% block extra_js %}
{% endblock %}